---
language: python

services: docker

env:
  - distro=centos6
  - distro=centos7
  - distro=ubuntu1404
  - distro=ubuntu1604


script:

  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # my test code
  - 'docker exec ${container_id} ls /usr/bin/htop | grep "/usr/bin/htop"'

after_script:
  - htop --version
  - htop --help